//! Scoring a window: block evidence → bits → the per-stage `b_j` ladder (ADR-0015 §1.3, §2.1,
//! §2.2, §13.1–§13.3; T-853 = MAUTO M-2).
//!
//! [`evaluate_window`] runs a recipe prefix over one window with `hk_blocks::run_window`, then
//! [`score_node`] turns each block's [`Evidence`] into credited bits:
//!
//! - **Analytic** metrics (S4–S6) keep the bits the block computed from its closed-form null
//!   (`hk_model::synth::null`), floored at 0.
//! - **Calibrated** metrics (S0–S3) are scored against the block's shipped table
//!   ([`CalibrationSet::builtin`]) at the window's fill and support. No table, no matching
//!   support, a window outside the table's fill population: [`Score::NoTable`], **0 bits**.
//!   Credited bits never exceed [`CALIBRATED_CLAIM_CAP_BITS`] (§13.2).
//! - **Groups** (§13.1): the table file's declared partition wins over the block's; a block
//!   publishing several calibrated metrics at a stage with no partition in its file is one
//!   group. Across blocks at one stage, a shared group key is one group (the maximum), and
//!   `undeclared` from two blocks is one group too — dependence nobody measured is not
//!   independence.
//!
//! [`StageLadder`] then holds `b_j` per stage and `Σ min(b_j, cap_j)`. **Not here:** the
//! look-elsewhere charge `L_j` (the engine's, M-3: it knows how many hypotheses ran), floors and
//! pruning (M-3), and the confirm gate (ADR-0022: analytic hold-out bits only).

use std::collections::BTreeMap;

use hk_blocks::{NodeEvidence, PortSlice, Registry, WindowError, WindowRun, run_window};
use hk_recipe::Recipe;

use crate::calibration::{CalibrationTable, Fill, LoadError, Score};
use crate::evidence::{Evidence, GroupId, combine_stage_bits, quality_from_bits};
use crate::stage::{CALIBRATED_CLAIM_CAP_BITS, Stage, default_cap_bits};

macro_rules! table {
    ($name:literal) => {
        (
            $name,
            include_str!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/../../synth/calibration/",
                $name,
                ".json"
            )),
        )
    };
}

/// The shipped `synth/calibration/<block>.json` files, generated by `python -m hkpy.calibrate
/// generate` over `crate::nullchain`'s corpora and re-checked by `tests/calibration_tables.rs`.
pub const BUILTIN_TABLES: &[(&str, &str)] = &[
    table!("lowpass"),
    table!("fm_demod"),
    table!("am_demod"),
    table!("fsk_demod"),
    table!("msk_demod"),
    table!("psk_demod"),
    table!("clock_recovery"),
    table!("slicer"),
    table!("nrzi"),
    table!("diff_decode"),
    table!("manchester"),
];

/// Calibration tables by `name@version`.
#[derive(Clone, Debug, Default)]
pub struct CalibrationSet {
    tables: BTreeMap<String, CalibrationTable>,
}

impl CalibrationSet {
    /// No tables: every calibrated metric scores `NoTable`.
    pub fn empty() -> Self {
        Self::default()
    }

    /// The shipped tables ([`BUILTIN_TABLES`]).
    pub fn builtin() -> Result<Self, LoadError> {
        let mut s = Self::empty();
        for (_, json) in BUILTIN_TABLES {
            s.insert(CalibrationTable::load(json)?);
        }
        Ok(s)
    }

    /// Adds (or replaces) a table under its `block`.
    pub fn insert(&mut self, t: CalibrationTable) {
        self.tables.insert(t.block().to_owned(), t);
    }

    /// The table for `name@version`. A block version with no table has none: a version bump
    /// invalidates the old one (§2.2).
    pub fn get(&self, block_version: &str) -> Option<&CalibrationTable> {
        self.tables.get(block_version)
    }

    /// Every table.
    pub fn iter(&self) -> impl Iterator<Item = &CalibrationTable> {
        self.tables.values()
    }
}

/// One evidence record, scored.
#[derive(Clone, Debug, PartialEq)]
pub struct Scored {
    /// Node id.
    pub node: String,
    /// `name@version`.
    pub block: String,
    /// The record with `bits` (and `quality`) credited and `group` as scored.
    pub evidence: Evidence,
    /// The table's answer, for a calibrated metric; `None` for an analytic one.
    pub score: Option<Score>,
}

/// Scores one node's evidence (see the module docs).
pub fn score_node(set: &CalibrationSet, node: &NodeEvidence, fill: Fill) -> Vec<Scored> {
    let block = node.block_version();
    let table = set.get(&block);
    let mut out: Vec<Scored> = node
        .evidence
        .iter()
        .map(|e| {
            let mut ev = *e;
            let score = if e.metric.is_analytic() {
                ev.bits = if e.bits.is_finite() {
                    e.bits.max(0.0)
                } else {
                    0.0
                };
                None
            } else {
                let s = match table {
                    Some(t) => t.score_raw(e.metric, e.raw, e.n, fill),
                    None => Score::NoTable {
                        cell: crate::calibration::CellId {
                            block: block.clone(),
                            metric: e.metric,
                            null: crate::calibration::NullKind::Noise,
                            n: e.n,
                            bucket: fill.bucket(),
                        },
                    },
                };
                ev.bits = s.credited_bits().clamp(0.0, CALIBRATED_CLAIM_CAP_BITS);
                if let Some(g) = table.and_then(|t| t.group_of(e.stage, e.metric)) {
                    ev.group = g;
                }
                Some(s)
            };
            ev.quality = quality_from_bits(ev.bits);
            Scored {
                node: node.id.clone(),
                block: block.clone(),
                evidence: ev,
                score,
            }
        })
        .collect();
    // §13.1: several calibrated metrics at a stage and no partition in the file → one group.
    for stage in Stage::ALL {
        let calibrated_here = |s: &Scored| s.evidence.stage == stage && s.score.is_some();
        let declared = table.is_some_and(|t| {
            out.iter()
                .filter(|s| calibrated_here(s))
                .all(|s| t.group_of(stage, s.evidence.metric).is_some())
        });
        if out.iter().filter(|s| calibrated_here(s)).count() > 1 && !declared {
            for s in out.iter_mut().filter(|s| calibrated_here(s)) {
                s.evidence.group = GroupId::Undeclared;
            }
        }
    }
    out
}

/// `b_j` per stage (§1.3 as amended by §13.1), before caps and look-elsewhere.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct StageLadder {
    /// `b_j`, or `None` where no block reported at that stage.
    pub bits: [Option<f32>; 7],
}

impl StageLadder {
    /// The ladder of a set of scored records (every block's, at every stage).
    pub fn of(scored: &[Scored]) -> Self {
        let mut bits = [None; 7];
        for stage in Stage::ALL {
            let at: Vec<&Evidence> = scored
                .iter()
                .map(|s| &s.evidence)
                .filter(|e| e.stage == stage)
                .collect();
            if !at.is_empty() {
                bits[stage.index() as usize] = Some(combine_stage_bits(at));
            }
        }
        Self { bits }
    }

    /// `b_j` at `stage`.
    pub fn stage_bits(&self, stage: Stage) -> Option<f32> {
        self.bits[stage.index() as usize]
    }

    /// `min(b_j, cap_j)` at `stage`.
    pub fn capped(&self, stage: Stage) -> Option<f32> {
        self.stage_bits(stage)
            .map(|b| default_cap_bits(stage).map_or(b, |c| b.min(c)))
    }

    /// `Σ_j min(b_j, cap_j)` — `evidence_bits` before the engine's look-elsewhere charge.
    pub fn total(&self) -> f32 {
        Stage::ALL.iter().filter_map(|&s| self.capped(s)).sum()
    }

    /// The deepest stage any block reported at.
    pub fn deepest(&self) -> Option<Stage> {
        Stage::ALL
            .iter()
            .rev()
            .copied()
            .find(|&s| self.stage_bits(s).is_some())
    }
}

/// One evaluated window.
#[derive(Debug)]
pub struct WindowEvidence {
    /// The raw run (outputs, per-node status and unscored evidence).
    pub run: WindowRun,
    /// Every node's records, scored, in topological order.
    pub scored: Vec<Scored>,
    /// The ladder over them.
    pub ladder: StageLadder,
}

/// Runs `recipe` over one window and scores it (see the module docs). `fill` is the window's
/// recorded ADC fill; an unknown σ scores every calibrated metric at 0 bits (§13.3).
pub fn evaluate_window(
    recipe: &Recipe,
    registry: &Registry,
    set: &CalibrationSet,
    rate_hz: f64,
    input: PortSlice<'_>,
    chunk_items: usize,
    fill: Fill,
) -> Result<WindowEvidence, WindowError> {
    let run = run_window(recipe, registry, rate_hz, input, chunk_items)?;
    let scored: Vec<Scored> = run
        .nodes
        .iter()
        .flat_map(|n| score_node(set, n, fill))
        .collect();
    let ladder = StageLadder::of(&scored);
    Ok(WindowEvidence {
        run,
        scored,
        ladder,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evidence::MetricId;
    use hk_blocks::EvidenceSet;

    fn node(block: &str, entries: &[Evidence]) -> NodeEvidence {
        let mut evidence = EvidenceSet::new();
        for e in entries {
            evidence.push(*e).unwrap();
        }
        NodeEvidence {
            id: "x".into(),
            block: block.into(),
            version: 1,
            evidence,
            status: Default::default(),
        }
    }

    const NOMINAL: Fill = Fill::new(8.0, 0.0);

    #[test]
    fn every_builtin_table_loads_and_declares_the_tight_fill_bounds() {
        let set = CalibrationSet::builtin().unwrap();
        assert_eq!(set.iter().count(), BUILTIN_TABLES.len());
        for t in set.iter() {
            // ADR-0015 §16.4: the first generation passed T-619's σ ≥ 1.0 LSB, clip ≤ 10 %.
            assert!(t.admits(Fill::new(1.0, 0.10)), "{}", t.block());
            assert!(!t.admits(Fill::new(0.9, 0.0)), "{}", t.block());
            assert!(!t.admits(Fill::new(2.0, 0.2)), "{}", t.block());
            assert!(!t.admits(Fill::default()), "unknown σ is under-filled");
            for c in t.cells() {
                let adm = t.admissible_bits(&c).unwrap();
                assert!(adm <= CALIBRATED_CLAIM_CAP_BITS, "{c:?}");
            }
        }
    }

    #[test]
    fn a_strong_signal_saturates_at_the_claim_cap_and_noise_earns_little() {
        let set = CalibrationSet::builtin().unwrap();
        let strong = Evidence::new(
            Stage::S1,
            MetricId::Bimodality,
            GroupId::DemodShape,
            0.9,
            4096,
            0.0,
        );
        let s = score_node(&set, &node("fsk_demod", &[strong]), NOMINAL);
        assert_eq!(s[0].evidence.bits, CALIBRATED_CLAIM_CAP_BITS);
        assert!(matches!(s[0].score, Some(Score::Saturated { .. })));
        // The null's median scores below one bit.
        let null = Evidence {
            raw: 0.16,
            ..strong
        };
        assert_eq!(
            score_node(&set, &node("fsk_demod", &[null]), NOMINAL)[0]
                .evidence
                .bits,
            0.0
        );
    }

    #[test]
    fn smaller_is_evidence_metrics_are_scored_in_the_evidence_direction() {
        let set = CalibrationSet::builtin().unwrap();
        let clean = Evidence::new(
            Stage::S1,
            MetricId::Evm,
            GroupId::Undeclared,
            0.1,
            1024,
            0.0,
        );
        let noisy = Evidence { raw: 1.3, ..clean };
        let b = |e| {
            score_node(&set, &node("psk_demod", &[e]), NOMINAL)[0]
                .evidence
                .bits
        };
        assert_eq!(b(clean), CALIBRATED_CLAIM_CAP_BITS);
        assert_eq!(b(noisy), 0.0);
    }

    #[test]
    fn a_support_off_the_table_an_unknown_block_and_under_fill_all_score_zero() {
        let set = CalibrationSet::builtin().unwrap();
        let e = Evidence::new(
            Stage::S1,
            MetricId::Evm,
            GroupId::Undeclared,
            0.1,
            1024,
            0.0,
        );
        let b =
            |block: &str, e: Evidence, fill| score_node(&set, &node(block, &[e]), fill)[0].clone();
        // 700 symbols: between the 256 and 1024 supports — not a table (the null moves with n).
        let off = b("psk_demod", Evidence { n: 700, ..e }, NOMINAL);
        assert!(matches!(off.score, Some(Score::NoTable { .. })));
        assert_eq!(off.evidence.bits, 0.0);
        // Just above the support, within the generator's own overshoot: the table.
        assert!(
            b("psk_demod", Evidence { n: 1030, ..e }, NOMINAL)
                .evidence
                .bits
                > 0.0
        );
        assert_eq!(b("no_such_block", e, NOMINAL).evidence.bits, 0.0);
        assert_eq!(b("psk_demod", e, Fill::new(0.3, 0.0)).evidence.bits, 0.0);
        assert_eq!(b("psk_demod", e, Fill::default()).evidence.bits, 0.0);
    }

    #[test]
    fn analytic_bits_pass_through_and_are_never_negative() {
        let set = CalibrationSet::builtin().unwrap();
        let sync = Evidence::new(
            Stage::S4,
            MetricId::SyncExcess,
            GroupId::Undeclared,
            12.0,
            12,
            40.0,
        );
        let s = score_node(&set, &node("sync_search", &[sync]), Fill::default());
        assert_eq!(
            s[0].evidence.bits, 40.0,
            "analytic nulls do not read the fill"
        );
        assert!(s[0].score.is_none());
        let bad = Evidence { bits: -3.0, ..sync };
        assert_eq!(
            score_node(&set, &node("sync_search", &[bad]), NOMINAL)[0]
                .evidence
                .bits,
            0.0
        );
    }

    #[test]
    fn the_files_groups_decide_and_the_ladder_takes_the_max_within_a_group() {
        let set = CalibrationSet::builtin().unwrap();
        // clock_recovery's file splits S2 into eye{eye_open} + soft_quality{timing_var}
        // (measured |ρ| < 0.3): two groups, so the stage sums them.
        let eye = Evidence::new(Stage::S2, MetricId::EyeOpen, GroupId::Eye, 0.99, 1024, 0.0);
        let tv = Evidence::new(
            Stage::S2,
            MetricId::TimingVar,
            GroupId::SoftQuality,
            0.001,
            1024,
            0.0,
        );
        let s = score_node(&set, &node("clock_recovery", &[eye, tv]), NOMINAL);
        let ladder = StageLadder::of(&s);
        assert_eq!(ladder.stage_bits(Stage::S2), Some(12.0));
        // manchester's file keeps both S3 metrics in bit_shape: the maximum, never the sum.
        let lv = Evidence::new(
            Stage::S3,
            MetricId::LineViolations,
            GroupId::BitShape,
            0.0,
            1024,
            0.0,
        );
        let bs = Evidence::new(
            Stage::S3,
            MetricId::BitStructure,
            GroupId::BitShape,
            0.5,
            1024,
            0.0,
        );
        let s = score_node(&set, &node("manchester", &[lv, bs]), NOMINAL);
        assert_eq!(StageLadder::of(&s).stage_bits(Stage::S3), Some(6.0));
        // A block claiming two groups with no file partition is one group.
        let s = score_node(
            &CalibrationSet::empty(),
            &node("clock_recovery", &[eye, tv]),
            NOMINAL,
        );
        assert!(s.iter().all(|x| x.evidence.group == GroupId::Undeclared));
    }

    #[test]
    fn the_ladder_caps_each_stage_and_sums_across_stages() {
        let mk = |stage, metric, bits| Scored {
            node: "n".into(),
            block: "b@1".into(),
            evidence: Evidence::new(stage, metric, GroupId::Undeclared, 0.0, 1, bits),
            score: None,
        };
        let l = StageLadder::of(&[
            mk(Stage::S4, MetricId::SyncExcess, 50.0),
            mk(Stage::S5, MetricId::CheckDistinctValid, 48.0),
            mk(Stage::S1, MetricId::Bimodality, 6.0),
        ]);
        assert_eq!(l.capped(Stage::S4), Some(32.0));
        assert_eq!(l.total(), 6.0 + 32.0 + 48.0);
        assert_eq!(l.deepest(), Some(Stage::S5));
        assert_eq!(l.stage_bits(Stage::S2), None);
    }
}
