[package]
name = "hk-demod"
description = "hackriff analog auto-mode demodulation, own digital demodulators and RDS"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
hk-core.workspace = true
hk-dsp.workspace = true
hk-model.workspace = true
