//! Symbol-clock consensus over a **population** of bursts (T-953).
//!
//! # The gap this closes
//!
//! T-614 made one burst's alphabet a measurement only when something independent of the trial
//! agreed with it ([`FskBurst::alphabet_evidence_framed`](super::FskBurst::alphabet_evidence_framed)):
//! a CRC, a confirmed sync prior, a learned sync word in the bits, or a clock C14 already trusted.
//! That is right for one burst — a 2-FSK demodulator always returns bits, so bits existing says
//! nothing — but it is the *only* rule, and below the C14 trust floor a real emitter that no
//! framing model fits abstains on every burst it ever sends. The emitter then gets **no
//! Demodulation row at all**, so `/api/inventory`'s `estimated_params` is `null`.
//!
//! The explorer measured exactly that against live air on 2026-09-25: over 585 pager bursts the
//! `/ws/open/bits` tap published a symbol rate per burst, clustered hard at 4800 / 9600 / 19200 /
//! 100000 Bd, while the emitters those bursts belonged to carried no parameters whatever.
//!
//! # Why a population is evidence where one burst is not
//!
//! Below the trust floor the receiver picks, per burst, the trial with the best lock quality out
//! of a fixed list ([`STANDARD_RATES_BD`](super::STANDARD_RATES_BD)) — several rates fit inside
//! the box, and the demodulator will return bits for every one of them. So under the null
//! hypothesis *"there is no symbol clock here"* the winning trial is whichever list entry happens
//! to fit that burst's noise best, and it is **not the same entry twice**: nothing in the
//! emission ties one burst's best-fitting rate to the next one's. Under the alternative *"there is
//! a symbol clock"* every burst is generated by the same clock, so the same list entry wins every
//! time and the **tracked** rates — measured from the Gardner loop's own symbol positions, not
//! from the seed — agree to well inside a per-cent.
//!
//! Agreement across many independent bursts is therefore evidence about the *emitter* that no
//! single burst carries, and it is the evidence a human reads off the tap. This module measures
//! it, and nothing else: it neither demodulates nor decides a family.
//!
//! # The rule
//!
//! Over the bursts offered:
//!
//! 1. a burst contributes only if its demodulation **locked** ([`FskLock::locked`](super::FskLock),
//!    timing RMS < 0.15 UI and eye opening > 0.2) with a finite tracked rate > 0, and its bits are
//!    **not periodic** — the [`periodic_bits`](super::periodic_bits) veto that catches a
//!    tone-modulated or unmodulated carrier is applied per burst here exactly as T-614 applies it;
//! 2. the contributing rates are clustered at [`CONSENSUS_TOLERANCE`] relative spacing;
//! 3. the largest cluster measures the emitter's symbol rate when it holds at least
//!    [`MIN_CONSENSUS_BURSTS`] bursts **and** at least [`CONSENSUS_FRACTION`] of the contributors.
//!
//! The reported rate is the cluster **median**, which is a better estimate of the emitter's clock
//! than any one burst's; the deviation and the burst duration are the medians of the same cluster.
//!
//! ## The constants, a priori
//!
//! - **[`CONSENSUS_TOLERANCE`] = 2 %.** The tracked rate is `fs·(N−1)/span` over the symbol
//!   positions of one burst, so its spread across bursts of one emitter is the timing jitter of
//!   the loop (RMS < 0.15 UI at lock) divided by the symbols integrated — well under 1 % on the
//!   ≥ 64-symbol bursts this path sees. Two per cent is that with margin, and still an order of
//!   magnitude tighter than the spacing of the standard-rate list (the closest neighbours in
//!   [`STANDARD_RATES_BD`](super::STANDARD_RATES_BD) differ by ≥ 20 %), so two *different* trials
//!   can never land in one cluster.
//! - **[`MIN_CONSENSUS_BURSTS`] = 6 and [`CONSENSUS_FRACTION`] = 0.75.** Under the null the
//!   winning trial is one of the `m ≥ 2` entries that fit the box, with no reason to repeat; the
//!   chance that ≥ 75 % of 6 draws land on one of them is `≤ 2·(C(6,5)·(1/2)⁶ + (1/2)⁶) = 0.22`
//!   at the worst case `m = 2`, and falls as `m⁻⁴` — 0.014 at `m = 3`, 0.003 at `m = 4`. Six is
//!   also the smallest population where the fraction can fail at all without the count deciding
//!   it alone. This is a *floor on the evidence*, not a false-alarm budget: the periodic-bits
//!   veto, the lock gate and the emitter's own detection all sit in front of it.
//!
//! # What it does not do
//!
//! A consensus is evidence about the **symbol clock**, so it licenses reporting the rate, the
//! deviation and the two-level alphabet that produced them. It is not a decode, it names no
//! service, and it sets no `known_status`: `family.rs`'s rule that a modulation names no service
//! is untouched.

use super::{FskBurst, PERIODIC_BITS_MIN_CORR, periodic_bits};

/// Relative spacing at which two tracked rates count as the same clock (see the module docs).
pub const CONSENSUS_TOLERANCE: f64 = 0.02;

/// Fewest bursts in the agreeing cluster for the population to measure a rate.
pub const MIN_CONSENSUS_BURSTS: usize = 6;

/// Least share of the contributing bursts the agreeing cluster must hold.
pub const CONSENSUS_FRACTION: f64 = 0.75;

/// What a population of bursts measured about its emitter's symbol clock.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RateConsensus {
    /// The agreed symbol rate: the median tracked rate of the cluster, Bd.
    pub rate_bd: f64,
    /// Median deviation of the cluster's bursts, Hz, when any measured one.
    pub deviation_hz: Option<f64>,
    /// Median duration of the cluster's bursts, s.
    pub burst_duration_s: f64,
    /// Bursts in the agreeing cluster.
    pub bursts: usize,
    /// Bursts that contributed a locked, non-periodic rate at all.
    pub contributors: usize,
    /// Largest relative distance from the cluster median, 0–1.
    pub spread: f64,
}

impl RateConsensus {
    /// Words for a provenance/evidence field.
    pub fn evidence(&self) -> String {
        format!(
            "{} of {} bursts agree on {:.1} Bd (±{:.2} %)",
            self.bursts,
            self.contributors,
            self.rate_bd,
            100.0 * self.spread
        )
    }
}

fn median(mut v: Vec<f64>) -> Option<f64> {
    if v.is_empty() {
        return None;
    }
    v.sort_by(f64::total_cmp);
    let n = v.len();
    Some(if n % 2 == 1 {
        v[n / 2]
    } else {
        0.5 * (v[n / 2 - 1] + v[n / 2])
    })
}

/// What one burst offers the consensus: the quantities it measured, and whether it may vote.
///
/// Extracted from an [`FskBurst`] by [`clock_sample`]; separated so the rule itself is a decision
/// over measurements, testable without a demodulator.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ClockSample {
    /// Tracked symbol rate, Bd (the Gardner loop's own, not the seed's).
    pub rate_bd: f64,
    /// Deviation at settled symbols, Hz, when measured.
    pub deviation_hz: Option<f64>,
    /// Burst duration, s.
    pub duration_s: f64,
    /// The burst locked, tracked a finite positive rate, and its bits are not periodic.
    pub usable: bool,
}

/// What `burst` offers the consensus (see [`ClockSample`]).
pub fn clock_sample(burst: &FskBurst) -> ClockSample {
    let d = burst.time_range();
    let duration_s = (d.duration_ns() as f64 / 1e9).max(0.0);
    let Some(s) = burst.symbols.as_ref() else {
        return ClockSample {
            rate_bd: 0.0,
            deviation_hz: None,
            duration_s,
            usable: false,
        };
    };
    let rate_bd = s.lock.tracked_rate_bd;
    // The T-614 veto, per burst: a tone or an unmodulated carrier repeats, data does not.
    let periodic = periodic_bits(&s.bits).is_some_and(|(_, r)| r >= PERIODIC_BITS_MIN_CORR);
    ClockSample {
        rate_bd,
        deviation_hz: s.deviation_hz,
        duration_s,
        usable: s.lock.locked && rate_bd.is_finite() && rate_bd > 0.0 && !periodic,
    }
}

/// The consensus of `samples`, and which of them it is built from (`true` per input index), or
/// `None` when the population does not agree (see the module docs for the rule).
pub fn consensus_of(samples: &[ClockSample]) -> Option<(RateConsensus, Vec<bool>)> {
    let usable: Vec<usize> = (0..samples.len()).filter(|&i| samples[i].usable).collect();
    if usable.len() < MIN_CONSENSUS_BURSTS {
        return None;
    }
    // Clusters at CONSENSUS_TOLERANCE: sorted by rate, split where the relative step exceeds it.
    // The standard-rate list is far coarser than the tolerance, so this cannot merge two trials.
    let mut order = usable.clone();
    order.sort_by(|a, b| samples[*a].rate_bd.total_cmp(&samples[*b].rate_bd));
    let mut best: Vec<usize> = Vec::new();
    let mut run: Vec<usize> = Vec::new();
    for &i in &order {
        let split = run.last().is_some_and(|&p| {
            (samples[i].rate_bd / samples[p].rate_bd - 1.0).abs() > CONSENSUS_TOLERANCE
        });
        if split {
            if run.len() > best.len() {
                best = std::mem::take(&mut run);
            } else {
                run.clear();
            }
        }
        run.push(i);
    }
    if run.len() > best.len() {
        best = run;
    }
    if best.len() < MIN_CONSENSUS_BURSTS
        || (best.len() as f64) < CONSENSUS_FRACTION * usable.len() as f64
    {
        return None;
    }
    let rate_bd = median(best.iter().map(|&i| samples[i].rate_bd).collect())?;
    let spread = best
        .iter()
        .map(|&i| (samples[i].rate_bd / rate_bd - 1.0).abs())
        .fold(0.0_f64, f64::max);
    let mut members = vec![false; samples.len()];
    for &i in &best {
        members[i] = true;
    }
    Some((
        RateConsensus {
            rate_bd,
            deviation_hz: median(
                best.iter()
                    .filter_map(|&i| samples[i].deviation_hz)
                    .collect(),
            ),
            burst_duration_s: median(best.iter().map(|&i| samples[i].duration_s).collect())
                .unwrap_or(0.0),
            bursts: best.len(),
            contributors: usable.len(),
            spread,
        },
        members,
    ))
}

/// The consensus of `bursts`, and which of them it is built from, or `None` when the population
/// does not agree.
pub fn rate_consensus_members(bursts: &[FskBurst]) -> Option<(RateConsensus, Vec<bool>)> {
    let samples: Vec<ClockSample> = bursts.iter().map(clock_sample).collect();
    consensus_of(&samples)
}

/// The consensus of `bursts`, or `None` when the population does not agree.
pub fn rate_consensus(bursts: &[FskBurst]) -> Option<RateConsensus> {
    rate_consensus_members(bursts).map(|(c, _)| c)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One burst as the receiver leaves it below the trust floor: a standard-rate trial nothing
    /// confirmed, locked, tracking `rate` over a 96 ms burst.
    fn sample(rate: f64) -> ClockSample {
        ClockSample {
            rate_bd: rate,
            deviation_hz: Some(4800.0),
            duration_s: 0.096,
            usable: true,
        }
    }

    fn population(rates: &[f64]) -> Vec<ClockSample> {
        rates.iter().copied().map(sample).collect()
    }

    fn consensus(rates: &[f64]) -> Option<RateConsensus> {
        consensus_of(&population(rates)).map(|(c, _)| c)
    }

    #[test]
    fn a_population_that_agrees_measures_the_clock_it_agrees_on() {
        // Eight pager-shaped bursts, tracked rates within the loop's own jitter of 1600 Bd.
        let rates = [
            1600.0, 1601.2, 1599.1, 1600.4, 1598.8, 1601.9, 1600.2, 1599.6,
        ];
        let c = consensus(&rates).expect("a population that agrees");
        assert_eq!((c.bursts, c.contributors), (8, 8));
        assert!((c.rate_bd - 1600.0).abs() < 2.0, "rate {}", c.rate_bd);
        assert!(c.spread < CONSENSUS_TOLERANCE, "spread {}", c.spread);
        assert_eq!(c.deviation_hz, Some(4800.0));
        assert!((c.burst_duration_s - 0.096).abs() < 1e-9);
        assert!(
            c.evidence().contains("8 of 8 bursts agree"),
            "{}",
            c.evidence()
        );
    }

    #[test]
    fn a_population_whose_best_trial_wanders_measures_nothing() {
        // The null: each burst's best-fitting standard rate is a different one.
        let rates = [
            1600.0, 4800.0, 2400.0, 9600.0, 1600.0, 19200.0, 4800.0, 2400.0,
        ];
        assert!(consensus(&rates).is_none());
    }

    #[test]
    fn too_few_bursts_measure_nothing_however_well_they_agree() {
        let rates = [1600.0, 1600.1, 1599.9, 1600.2, 1600.0];
        assert_eq!(rates.len(), MIN_CONSENSUS_BURSTS - 1);
        assert!(consensus(&rates).is_none());
        // One more of the same clock, and the population measures it.
        let rates = [1600.0, 1600.1, 1599.9, 1600.2, 1600.0, 1600.3];
        assert!(consensus(&rates).is_some());
    }

    #[test]
    fn only_usable_bursts_vote() {
        // Eight bursts at one rate, none of them usable (unlocked, or periodic bits).
        let mut p = population(&[1600.0; 8]);
        for s in &mut p {
            s.usable = false;
        }
        assert!(consensus_of(&p).is_none(), "an unusable population");
        // Six usable among them is enough; the rest are not counted at all.
        for s in p.iter_mut().take(6) {
            s.usable = true;
        }
        let (c, members) = consensus_of(&p).expect("six usable bursts agree");
        assert_eq!((c.bursts, c.contributors), (6, 6));
        assert_eq!(members.iter().filter(|m| **m).count(), 6);
        assert!(!members[7], "an unusable burst is not a member");
    }

    #[test]
    fn a_minority_that_agrees_inside_a_scattered_population_does_not_carry_it() {
        // Six bursts on one rate, but only half the population: the fraction rule refuses.
        let mut rates = vec![1600.0; 6];
        rates.extend([2400.0, 4800.0, 9600.0, 19200.0, 2400.0, 4800.0]);
        assert!(consensus(&rates).is_none());
        // Enough agreeing bursts to clear 75 % and it measures.
        let mut rates = vec![1600.0; 12];
        rates.extend([2400.0, 4800.0]);
        let c = consensus(&rates).expect("12 of 14 agree");
        assert_eq!((c.bursts, c.contributors), (12, 14));
    }

    #[test]
    fn two_standard_rates_never_fall_into_one_cluster() {
        // The closest neighbours in the standard-rate list are 20 % apart; the tolerance is 2 %.
        let rates = [1200.0, 1200.0, 1200.0, 1440.0, 1440.0, 1440.0];
        assert!(
            consensus(&rates).is_none(),
            "two distinct rates must not merge into one agreeing cluster"
        );
    }
}
