//! Shared helpers for the T-009 scheduler tests: plan builders, synthetic runs, golden files.

#![allow(dead_code)]

use std::path::Path;

use hk_core::SourceCapabilities;
use hk_core::scheduler::{
    GainSlot, Purpose, ScheduleStep, Scheduler, SchedulerConfig, SyntheticClock,
};
use hk_model::{
    FreqRange, GainTableEntry, PlanRegion, ScanPlan, ScanPlanId, ScanPolicy, Schedule, Timestamp,
};
use serde_json::{Value, json};

/// 2026-09-13T00:00:00Z.
pub const T0_NS: i64 = 1_789_257_600_000_000_000;
pub const MHZ: f64 = 1e6;
pub const S: i64 = 1_000_000_000;

pub fn plan_id() -> ScanPlanId {
    "01926f3a-0000-7000-8000-000000000009".parse().unwrap()
}

pub fn region(lo_mhz: f64, hi_mhz: f64, priority: f64, revisit_s: Option<f64>) -> PlanRegion {
    PlanRegion {
        freq: FreqRange::new(lo_mhz * MHZ, hi_mhz * MHZ),
        priority,
        revisit_ns: revisit_s.map(|s| (s * 1e9).round() as i64),
    }
}

pub fn gain(
    lo_mhz: f64,
    hi_mhz: f64,
    lna_db: f64,
    vga_db: f64,
    amp_on: bool,
    port: Option<&str>,
) -> GainTableEntry {
    GainTableEntry {
        freq: FreqRange::new(lo_mhz * MHZ, hi_mhz * MHZ),
        lna_db,
        vga_db,
        amp_on,
        antenna_port: port.map(Into::into),
    }
}

pub fn plan(
    name: &str,
    version: u32,
    regions: Vec<PlanRegion>,
    policy: ScanPolicy,
    gain_table: Vec<GainTableEntry>,
    extra: Value,
) -> ScanPlan {
    ScanPlan {
        id: plan_id(),
        version,
        name: name.into(),
        created_at: Timestamp::from_unix_nanos(T0_NS),
        regions,
        policy,
        gain_table,
        schedule: Schedule::Continuous,
        extra,
    }
}

pub fn clock() -> SyntheticClock {
    SyntheticClock::new(Timestamp::from_unix_nanos(T0_NS))
}

/// A HackRF One scheduler for `plan` with the plan's settings, on a synthetic clock at T0.
pub fn hackrf(plan: &ScanPlan) -> Scheduler<SyntheticClock> {
    Scheduler::new(
        plan,
        SchedulerConfig::from_plan(plan).unwrap(),
        &SourceCapabilities::hackrf_one(),
        clock(),
    )
    .unwrap()
}

/// Emits `n` steps, advancing the clock by each step's duration.
pub fn run(s: &mut Scheduler<SyntheticClock>, n: usize) -> Vec<ScheduleStep> {
    let mut out = Vec::with_capacity(n);
    s.run_synthetic(n, &mut out);
    out
}

pub fn purpose_json(p: &Purpose) -> Value {
    match *p {
        Purpose::Sweep { hop } => json!({ "kind": "sweep", "hop": hop }),
        Purpose::RegionDwell { hop } => json!({ "kind": "region-dwell", "hop": hop }),
        Purpose::Dwell { poi } => json!({ "kind": "dwell", "poi": poi }),
        Purpose::GainStep { poi, pair, slot } => json!({
            "kind": "gain-step",
            "poi": poi,
            "pair": pair,
            "slot": match slot { GainSlot::A => "A", GainSlot::B => "B" },
        }),
        Purpose::Retune { poi, delta_hz } => {
            json!({ "kind": "retune", "poi": poi, "delta_hz": delta_hz })
        }
        Purpose::RateChange { poi, base_rate_hz } => {
            json!({ "kind": "rate-change", "poi": poi, "base_rate_hz": base_rate_hz })
        }
        Purpose::UserIntent { intent } => json!({ "kind": "user-intent", "intent": intent }),
        other => json!({ "kind": other.name() }),
    }
}

pub fn step_json(s: &ScheduleStep) -> Value {
    json!({
        "seq": s.seq,
        "t_offset_ns": s.t_start.as_unix_nanos() - T0_NS,
        "duration_ns": s.duration_ns,
        "center_hz": s.center_hz,
        "rate_hz": s.rate_hz,
        "baseband_filter_hz": s.baseband_filter_hz,
        "lna_db": s.gains.lna_db,
        "vga_db": s.gains.vga_db,
        "amp_on": s.gains.amp_on,
        "gain_entry": s.gain_entry,
        "accessory": s.accessory,
        "rf_path": s.rf_path,
        "purpose": purpose_json(&s.purpose),
        "plan_version": s.plan_version,
    })
}

/// Compares the compiled plan summary and `steps` with `tests/golden/<name>.json`. Set
/// `HK_UPDATE_GOLDEN=1` to regenerate deliberately.
pub fn check_golden(name: &str, s: &Scheduler<SyntheticClock>, steps: &[ScheduleStep]) {
    let p = s.plan();
    let doc = json!({
        "note": "Generated by crates/hk-core/tests/scheduler_golden.rs; regenerate deliberately with HK_UPDATE_GOLDEN=1 and review the diff.",
        "plan_version": p.plan_version,
        "usable_span_hz": p.usable_span_hz,
        "pass_ns": p.pass_ns,
        "dwell_slots_per_pass": p.dwell_slots_per_pass,
        "dwell_cap_ns": p.dwell_cap_ns,
        "verification_group_ns": p.verification_group_ns,
        "revisit_bound_ns": p.revisit_bound_ns,
        "warnings": p.warnings.iter().map(|w| format!("{w:?}")).collect::<Vec<_>>(),
        "hops": p.hops.iter().map(|h| json!({
            "kind": format!("{:?}", h.kind),
            "center_hz": h.center_hz,
            "covers_hz": [h.covers.lo_hz, h.covers.hi_hz],
            "rf_path": h.rf_path,
            "region": h.region,
            "accessory": h.accessory,
        })).collect::<Vec<_>>(),
        "steps": steps.iter().map(step_json).collect::<Vec<_>>(),
    });
    let text = serde_json::to_string_pretty(&doc).unwrap() + "\n";
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/golden")
        .join(format!("{name}.json"));
    if std::env::var_os("HK_UPDATE_GOLDEN").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &text).unwrap();
        return;
    }
    let stored = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "{}: {e}; generate it with HK_UPDATE_GOLDEN=1",
            path.display()
        )
    });
    let expected: Value = serde_json::from_str(&stored).unwrap();
    let actual: Value = serde_json::from_str(&text).unwrap();
    if expected != actual {
        let (e, a) = (&expected["steps"], &actual["steps"]);
        let n = e
            .as_array()
            .map_or(0, Vec::len)
            .max(a.as_array().map_or(0, Vec::len));
        match (0..n).find(|&i| e.get(i) != a.get(i)) {
            Some(i) => panic!(
                "{name}: step {i} differs from the golden file\n expected {}\n actual   {}\n(regenerate deliberately with HK_UPDATE_GOLDEN=1)",
                e.get(i).map_or("<none>".into(), Value::to_string),
                a.get(i).map_or("<none>".into(), Value::to_string)
            ),
            None => panic!(
                "{name}: plan summary differs from the golden file\n expected {}\n actual   {}",
                Value::Object(
                    expected
                        .as_object()
                        .unwrap()
                        .clone()
                        .into_iter()
                        .filter(|(k, _)| k != "steps")
                        .collect()
                ),
                Value::Object(
                    actual
                        .as_object()
                        .unwrap()
                        .clone()
                        .into_iter()
                        .filter(|(k, _)| k != "steps")
                        .collect()
                )
            ),
        }
    }
}

/// T-120: a blind candidate in cell `cell` (score from SNR 20 dB, `novelty`, unknown class).
#[allow(dead_code)]
pub fn candidate(
    cell: i64,
    center_mhz: f64,
    bw_khz: f64,
    novelty: f64,
    needs_verification: bool,
) -> hk_model::attention::score::Candidate {
    use hk_model::attention::baseline::{BaselineResolution, Maturity};
    use hk_model::attention::score::{
        Candidate, CandidateSubject, NoveltyScore, ScoreComponents, ScoreWeights, interestingness,
        normalised,
    };
    let w = ScoreWeights::default();
    let components = ScoreComponents {
        snr_db: Some(20.0),
        novelty,
        class_entropy: None,
        decoder_available: false,
        periodicity: None,
        boring_prior: 0.0,
    };
    let score = interestingness(&w, &components);
    Candidate {
        subject: CandidateSubject::Cells {
            scheme: 7,
            lo_cell: cell,
            hi_cell: cell,
        },
        freq: FreqRange::centered(center_mhz * MHZ, bw_khz * 1e3),
        score,
        score_norm: normalised(&w, score),
        components,
        novelty: NoveltyScore {
            novelty,
            level_z: None,
            occupancy_z: None,
            new_emitter: Some(novelty),
            observed_s: 60.0,
            maturity: Maturity::Mature {
                resolution: BaselineResolution::AllHours,
            },
            provenance_explained: false,
        },
        suspect_fraction: if needs_verification { 1.0 } else { 0.0 },
        needs_verification,
        expected_interval_s: None,
        min_on_off_s: None,
        next_burst_eta: None,
    }
}

/// T-120: the scheduler key of [`candidate`]`(cell, ..)`.
#[allow(dead_code)]
pub fn candidate_key(cell: i64) -> u64 {
    hk_core::scheduler::bandit::subject_key(&hk_model::attention::score::CandidateSubject::Cells {
        scheme: 7,
        lo_cell: cell,
        hi_cell: cell,
    })
}

/// T-120: publishes `candidates` (sorted by score) at `t`.
#[allow(dead_code)]
pub fn publish_candidates(
    provider: &hk_model::attention::score::SharedInterestingness,
    t: Timestamp,
    mut candidates: Vec<hk_model::attention::score::Candidate>,
) {
    candidates.sort_by(|a, b| b.score.total_cmp(&a.score));
    let mut set = hk_model::attention::score::CandidateSet::empty(t);
    set.candidates = candidates;
    provider.publish(set).unwrap();
}
